
services:
  - type: web
    name: mcp-endpoint
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BASIC_AUTH_USERNAME
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
